# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: My Profile
email: bkim19302@gmail.com
author: Brian Kim
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description.
copyright: 'Copyright &copy; 2015 O'Brian Kim. All Rights Reserved.'
credits: "O'Brian Finch"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/BrioKimm
  - title: github
    url: https://github.com/kimobrian
  - title: linkedin
    url: https://www.linkedin.com/in/o-brian-kimokot-a92b60100/
